// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LaborPro.Automation.Features.Allowances
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Verify Allowances Module")]
    [NUnit.Framework.CategoryAttribute("LaborPro")]
    [NUnit.Framework.CategoryAttribute("Regression")]
    [NUnit.Framework.CategoryAttribute("Allowance")]
    public partial class VerifyAllowancesModuleFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "LaborPro",
                "Regression",
                "Allowance"};
        
#line 1 "Allowance.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Allowances", "Verify Allowances Module", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01. Launch Browser and Login to the Application")]
        [NUnit.Framework.CategoryAttribute("Setup")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public void _01_LaunchBrowserAndLoginToTheApplication()
        {
            string[] tagsOfScenario = new string[] {
                    "Setup",
                    "Smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01. Launch Browser and Login to the Application", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    testRunner.Given("User launched \"$browser\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
    testRunner.When("User go to application \"$url\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
    testRunner.Then("User enter email: \"$username_1\" and password: \"$password_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
    testRunner.And("Verify Login message: \"success\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02. verify_add_allowance_name_empty_tag")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public void _02_Verify_Add_Allowance_Name_Empty_Tag()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02. verify_add_allowance_name_empty_tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 13
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table2.AddRow(new string[] {
                            "Name",
                            ""});
#line 14
    testRunner.When("User add allowance using below input", ((string)(null)), table2, "When ");
#line hidden
#line 17
    testRunner.Then("Verify validation Message: \"Name is required\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
    testRunner.And("User click on cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03. verify_add_allowance_name_already_exist")]
        public void _03_Verify_Add_Allowance_Name_Already_Exist()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03. verify_add_allowance_name_already_exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
    testRunner.Then("User delete allowance \"Allowance to verify duplicate record\" if exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table3.AddRow(new string[] {
                            "Name",
                            "Allowance to verify duplicate record"});
                table3.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "300"});
                table3.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table3.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table3.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table3.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table3.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "10"});
                table3.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "20"});
                table3.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "80"});
#line 24
    testRunner.When("User add allowance using below input", ((string)(null)), table3, "When ");
#line hidden
#line 35
    testRunner.Then("User verify created allowance name \"Allowance to verify duplicate record\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 36
    testRunner.And("User click on previous link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table4.AddRow(new string[] {
                            "Name",
                            "Allowance to verify duplicate record"});
                table4.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "300"});
                table4.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table4.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table4.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table4.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table4.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "10"});
                table4.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "20"});
                table4.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "80"});
#line 37
    testRunner.When("User add allowance using below input", ((string)(null)), table4, "When ");
#line hidden
#line 49
    testRunner.Then("Verify validation Message: \"Name already exists\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
    testRunner.And("User click on cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
    testRunner.And("User delete created allowance: \"Allowance to verify duplicate record\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04. verify_add_allowance_by_adding_correct_record_of_name")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public void _04_Verify_Add_Allowance_By_Adding_Correct_Record_Of_Name()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04. verify_add_allowance_by_adding_correct_record_of_name", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
    testRunner.Then("User delete allowance \"Allowance by adding correct name\" if exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table5.AddRow(new string[] {
                            "Name",
                            "Allowance by adding correct name"});
                table5.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "300"});
                table5.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table5.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table5.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table5.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table5.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "10"});
                table5.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "20"});
                table5.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "80"});
#line 58
    testRunner.When("User add allowance using below input", ((string)(null)), table5, "When ");
#line hidden
#line 69
    testRunner.Then("User verify created allowance name \"Allowance by adding correct name\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 70
    testRunner.And("User delete allowance record", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05. verify_add_allowance_paid_time_empty")]
        public void _05_Verify_Add_Allowance_Paid_Time_Empty()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05. verify_add_allowance_paid_time_empty", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 73
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table6.AddRow(new string[] {
                            "Name",
                            "Allowance by adding without paid time"});
                table6.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            ""});
#line 74
    testRunner.When("User add allowance using below input", ((string)(null)), table6, "When ");
#line hidden
#line 78
    testRunner.Then("Verify validation Message: \"Paid Time must be between 200 and 720\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
    testRunner.And("User click on cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06. verify_add_allowance_paid_time_range_200_and_720")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public void _06_Verify_Add_Allowance_Paid_Time_Range_200_And_720()
        {
            string[] tagsOfScenario = new string[] {
                    "Smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06. verify_add_allowance_paid_time_range_200_and_720", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 83
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table7.AddRow(new string[] {
                            "Name",
                            "Verify add allowance paid time range"});
                table7.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "150"});
                table7.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table7.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table7.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table7.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table7.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "10"});
                table7.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "20"});
                table7.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "80"});
#line 84
    testRunner.When("User add allowance using below input", ((string)(null)), table7, "When ");
#line hidden
#line 95
    testRunner.Then("Verify validation Message: \"Paid Time must be between 200 and 720\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
    testRunner.And("User click on cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07. verify_add_allowance_paid_time_value_getting_added_when_value_is_supplied_in_" +
            "range")]
        public void _07_Verify_Add_Allowance_Paid_Time_Value_Getting_Added_When_Value_Is_Supplied_In_Range()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07. verify_add_allowance_paid_time_value_getting_added_when_value_is_supplied_in_" +
                    "range", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 99
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 100
    testRunner.Then("User delete allowance \"Allowance paid time value in range\" if exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table8.AddRow(new string[] {
                            "Name",
                            "Allowance paid time value in range"});
                table8.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "300"});
                table8.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table8.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table8.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table8.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table8.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "10"});
                table8.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "20"});
                table8.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "80"});
#line 101
    testRunner.When("User add allowance using below input", ((string)(null)), table8, "When ");
#line hidden
#line 112
    testRunner.Then("User verify created allowance name \"Allowance paid time value in range\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
    testRunner.And("User delete allowance record", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08. verify_add_allowance_Incentive_Opportunity_Allowance_Percent")]
        public void _08_Verify_Add_Allowance_Incentive_Opportunity_Allowance_Percent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08. verify_add_allowance_Incentive_Opportunity_Allowance_Percent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 115
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 116
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 117
    testRunner.Then("User delete allowance \"Allowance Incentive Opportunity Percent\" if exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table9.AddRow(new string[] {
                            "Name",
                            "Allowance Incentive Opportunity Percent"});
                table9.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "300"});
                table9.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table9.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table9.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table9.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table9.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "10"});
                table9.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "20"});
                table9.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "125"});
#line 118
    testRunner.When("User add allowance using below input", ((string)(null)), table9, "When ");
#line hidden
#line 129
    testRunner.Then("User verify created allowance name \"Allowance Incentive Opportunity Percent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 130
    testRunner.And("User delete allowance record", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09. verify_Add_allowance_Minor_Unavoidable_delay_percent_and_Additional_Percent_r" +
            "ange_value_less_than_100")]
        public void _09_Verify_Add_Allowance_Minor_Unavoidable_Delay_Percent_And_Additional_Percent_Range_Value_Less_Than_100()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09. verify_Add_allowance_Minor_Unavoidable_delay_percent_and_Additional_Percent_r" +
                    "ange_value_less_than_100", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 132
   this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 133
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table10.AddRow(new string[] {
                            "Name",
                            "Verify Calculated Allowance Percent"});
                table10.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "300"});
                table10.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table10.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table10.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table10.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table10.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "200"});
                table10.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "20"});
                table10.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "125"});
#line 134
    testRunner.When("User add allowance using below input to verify validation message", ((string)(null)), table10, "When ");
#line hidden
#line 145
    testRunner.Then("User verify error alert message: \"Calculated Allowance Percent must be less than " +
                        "100%\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 146
    testRunner.And("User click on cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Key",
                            "Value"});
                table11.AddRow(new string[] {
                            "Name",
                            "Dummy"});
                table11.AddRow(new string[] {
                            "Paid Time (Minutes)",
                            "300"});
                table11.AddRow(new string[] {
                            "Excluded Paid Breaks (Minutes)",
                            "10"});
                table11.AddRow(new string[] {
                            "Relief Time (Minutes)",
                            "1"});
                table11.AddRow(new string[] {
                            "Included Paid Breaks (Minutes)",
                            "20"});
                table11.AddRow(new string[] {
                            "Rest Calculation",
                            "Rest"});
                table11.AddRow(new string[] {
                            "Minor Unavoidable Delay (Percent)",
                            "20"});
                table11.AddRow(new string[] {
                            "Additional Delay (Percent)",
                            "200"});
                table11.AddRow(new string[] {
                            "Incentive Opportunity Allowance (Percent)",
                            "125"});
#line 147
    testRunner.When("User add allowance using below input to verify validation message", ((string)(null)), table11, "When ");
#line hidden
#line 158
    testRunner.Then("User verify error alert message: \"Calculated Allowance Percent must be less than " +
                        "100%\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 159
    testRunner.And("User click on cancel Button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10. Logout and Close Browser")]
        [NUnit.Framework.CategoryAttribute("Cleanup")]
        [NUnit.Framework.CategoryAttribute("Smoke")]
        public void _10_LogoutAndCloseBrowser()
        {
            string[] tagsOfScenario = new string[] {
                    "Cleanup",
                    "Smoke"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10. Logout and Close Browser", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 162
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 163
    testRunner.Given("User navigates to the Allowance tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 164
    testRunner.When("User logout from the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 165
    testRunner.Then("User close browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
