  # Variable 'Parameters.Inputs.version' was defined in the Variables tab
variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.tabName
  value: HTML-Report
name: $(date:yyyyMMdd)$(rev:.r)
 
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
  - task: UseDotNet@2
    displayName: Use .NET Core sdk 6.0.101
    inputs:
      version: 6.0.101
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
      feedRestore: bcdc91ac-8f9e-44c5-9298-ed2be33c5f9b
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      zipAfterPublish: false
      modifyOutputPath: false
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
  - task: VSTest@2
    displayName: VsTest - testAssemblies
    inputs:
      testAssemblyVer2: >-
        **\laborpro.dll

        !**\*TestAdapter.dll

        !**\obj\**

        !**\bin\**\ref\**
  
  - task: PublishHtmlReport@1
    inputs:
      reportDir: 'report/index.html'