parameters:
- name: ENV
  displayName: Environment Configuration 
  type: string
  values:
  - bits 
  - uat-
  - dev
  - prereleaseuat
  - blankdb_automation

stages:
  - stage: SmokeTesting
    variables:
    - name: BuildParameters.RestoreBuildProjects
      value: '**/LaborPro.Automation.csproj'
    - name: ENV
      value: ${{parameters.ENV}}
    pool:  
      vmImage: windows-latest
    jobs:
    - job: SmokeTestAutomation
      displayName: BITSTestAutomationExecution 
      steps:
      - checkout: self
        clean: true
      - task: UseDotNet@2
        displayName: Use .NET Core sdk 6.0.101
        inputs:
          packageType: sdk
          version: 6.0.101
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: $(BuildParameters.RestoreBuildProjects)
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: $(BuildParameters.RestoreBuildProjects)
          arguments: --configuration $(BuildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: Publish
        inputs:
          command: publish
          publishWebProjects: false
          projects: $(BuildParameters.RestoreBuildProjects)
          arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
          zipAfterPublish: true
          modifyOutputPath: false 
      
      - task: DotNetCoreCLI@2
        displayName: 'dotnet test'
        inputs:
          command: test
          projects: '**/*.csproj'
        continueOnError: true
        condition: always()

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          PathtoPublish: report
          ArtifactName: report
        continueOnError: true
        condition: always()

      - task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1
        displayName: 'Publish Html Report'
        inputs:
          reportDir: report/index.html
        continueOnError: true
        condition: always()